name: Latest blogpost workflow
on: 
    schedule:
        - cron: '0 * * * *'
permissions:
    contents: write
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout 
              uses: actions/checkout@v3
            - name: Blog Post Workflow
              uses: gautamkrishnar/blog-post-workflow@1.8.2
              with: 
                max_post_count: "4"
                feed_list: "https://aniketpr01.medium.com/feed"
